apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extended-ceph-exporter.fullname" . }}
  labels:
    {{- include "extended-ceph-exporter.labels" . | nindent 4 }}
data:
  CEPH_METRICS_RGW_HOST: {{ include "extended-ceph-exporter.rgwHost" . | b64enc }}
  CEPH_METRICS_RGW_ACCESS_KEY: {{ .Values.config.rgw.accessKey | default (randAlphaNum 20) | b64enc }}
  CEPH_METRICS_RGW_SECRET_KEY: {{ .Values.config.rgw.secretKey | default (randAlphaNum 40) | b64enc }}
{{- range $k, $v := .Values.additionalEnv }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
