name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19"

      - name: Run tests
        run: |
          make test
          make promu
          make check_license
